<?php

namespace Container9MEhC3w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvFootwearImportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Command\csvFootwearImport' shared autowired service.
     *
     * @return \App\Command\csvFootwearImport
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Console/AbstractCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Command/csvFootwearImport.php';

        return $container->services['console.command.public_alias.App\\Command\\csvFootwearImport'] = new \App\Command\csvFootwearImport();
    }
}
