<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMaymx7M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMaymx7M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMaymx7M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMaymx7M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMaymx7M\App_KernelDevDebugContainer([
    'container.build_hash' => 'Maymx7M',
    'container.build_id' => 'df8a2180',
    'container.build_time' => 1673849203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMaymx7M');
