<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQw6xm6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQw6xm6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQw6xm6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQw6xm6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIQw6xm6\App_KernelDevDebugContainer([
    'container.build_hash' => 'IQw6xm6',
    'container.build_id' => '62dd3b2b',
    'container.build_time' => 1673609438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQw6xm6');
